[2020-11-28 18:02:43,761] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Write_data_to_postgres_then_to_elasticsearch.Create_table_in_postgres 2020-11-28T12:32:39.324840+00:00 [queued]>
[2020-11-28 18:02:43,813] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Write_data_to_postgres_then_to_elasticsearch.Create_table_in_postgres 2020-11-28T12:32:39.324840+00:00 [queued]>
[2020-11-28 18:02:43,813] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-11-28 18:02:43,813] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-11-28 18:02:43,813] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-11-28 18:02:43,831] {taskinstance.py:901} INFO - Executing <Task(PostgresOperator): Create_table_in_postgres> on 2020-11-28T12:32:39.324840+00:00
[2020-11-28 18:02:43,833] {standard_task_runner.py:54} INFO - Started process 12931 to run task
[2020-11-28 18:02:43,859] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Write_data_to_postgres_then_to_elasticsearch', 'Create_table_in_postgres', '2020-11-28T12:32:39.324840+00:00', '--job_id', '408', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/csv_pg_elasticsearch.py', '--cfg_path', '/var/folders/ff/pqhf5klx0msdsn3m1cnq4cxr0000gn/T/tmpgr71d93t']
[2020-11-28 18:02:43,862] {standard_task_runner.py:78} INFO - Job 408: Subtask Create_table_in_postgres
[2020-11-28 18:02:43,906] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Write_data_to_postgres_then_to_elasticsearch.Create_table_in_postgres 2020-11-28T12:32:39.324840+00:00 [running]> 47.43.168.192.in-addr.arpa
[2020-11-28 18:02:43,935] {postgres_operator.py:62} INFO - Executing: CREATE TABLE sampletable(
            id integer PRIMARY KEY,
            description text,
            name text,
            id1 text,
            id2 text,
            department text
        );
        SET client_encoding = WIN1252;
        
[2020-11-28 18:02:43,946] {base_hook.py:89} INFO - Using connection to: id: postgres_default. Host: localhost, Port: None, Schema: testdb, Login: testuser, Password: XXXXXXXX, extra: None
[2020-11-28 18:02:43,951] {dbapi_hook.py:174} INFO - CREATE TABLE sampletable(
            id integer PRIMARY KEY,
            description text,
            name text,
            id1 text,
            id2 text,
            department text
        );
        SET client_encoding = WIN1252;
        
[2020-11-28 18:02:43,953] {taskinstance.py:1150} ERROR - relation "sampletable" already exists
Traceback (most recent call last):
  File "/Users/yudi/opt/anaconda3/envs/airflow/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/yudi/opt/anaconda3/envs/airflow/lib/python3.6/site-packages/airflow/operators/postgres_operator.py", line 65, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/Users/yudi/opt/anaconda3/envs/airflow/lib/python3.6/site-packages/airflow/hooks/dbapi_hook.py", line 175, in run
    cur.execute(s)
psycopg2.errors.DuplicateTable: relation "sampletable" already exists

[2020-11-28 18:02:43,956] {taskinstance.py:1194} INFO - Marking task as FAILED. dag_id=Write_data_to_postgres_then_to_elasticsearch, task_id=Create_table_in_postgres, execution_date=20201128T123239, start_date=20201128T123243, end_date=20201128T123243
[2020-11-28 18:02:48,711] {local_task_job.py:102} INFO - Task exited with return code 1
