[2020-11-28 18:06:31,754] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Write_data_to_postgres_then_to_elasticsearch.Write_csv_data_to_db 2020-11-28T12:36:17.649224+00:00 [queued]>
[2020-11-28 18:06:31,777] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Write_data_to_postgres_then_to_elasticsearch.Write_csv_data_to_db 2020-11-28T12:36:17.649224+00:00 [queued]>
[2020-11-28 18:06:31,777] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-11-28 18:06:31,778] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-11-28 18:06:31,778] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-11-28 18:06:31,792] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Write_csv_data_to_db> on 2020-11-28T12:36:17.649224+00:00
[2020-11-28 18:06:31,794] {standard_task_runner.py:54} INFO - Started process 14140 to run task
[2020-11-28 18:06:31,816] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Write_data_to_postgres_then_to_elasticsearch', 'Write_csv_data_to_db', '2020-11-28T12:36:17.649224+00:00', '--job_id', '416', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/csv_pg_elasticsearch.py', '--cfg_path', '/var/folders/ff/pqhf5klx0msdsn3m1cnq4cxr0000gn/T/tmpqjwcs_3k']
[2020-11-28 18:06:31,819] {standard_task_runner.py:78} INFO - Job 416: Subtask Write_csv_data_to_db
[2020-11-28 18:06:31,865] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Write_data_to_postgres_then_to_elasticsearch.Write_csv_data_to_db 2020-11-28T12:36:17.649224+00:00 [running]> 47.43.168.192.in-addr.arpa
[2020-11-28 18:06:31,894] {logging_mixin.py:112} INFO - this is the reader
[2020-11-28 18:06:31,894] {logging_mixin.py:112} INFO - <_io.TextIOWrapper name='data.csv' mode='r' encoding='UTF-8'>
[2020-11-28 18:06:31,894] {logging_mixin.py:112} INFO - the endd
[2020-11-28 18:06:31,894] {taskinstance.py:1150} ERROR - 'utf-8' codec can't decode byte 0xae in position 119: invalid start byte
Traceback (most recent call last):
  File "/Users/yudi/opt/anaconda3/envs/airflow/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/yudi/opt/anaconda3/envs/airflow/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/Users/yudi/opt/anaconda3/envs/airflow/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/yudi/airflow/dags/csv_pg_elasticsearch.py", line 57, in write_data
    for row in reader:
  File "/Users/yudi/opt/anaconda3/envs/airflow/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 119: invalid start byte
[2020-11-28 18:06:31,899] {taskinstance.py:1194} INFO - Marking task as FAILED. dag_id=Write_data_to_postgres_then_to_elasticsearch, task_id=Write_csv_data_to_db, execution_date=20201128T123617, start_date=20201128T123631, end_date=20201128T123631
[2020-11-28 18:06:36,744] {local_task_job.py:102} INFO - Task exited with return code 1
