[2020-11-28 18:15:19,793] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Write_data_to_postgres_then_to_elasticsearch.Write_csv_data_to_db 2020-11-28T12:45:10.631103+00:00 [queued]>
[2020-11-28 18:15:19,839] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: Write_data_to_postgres_then_to_elasticsearch.Write_csv_data_to_db 2020-11-28T12:45:10.631103+00:00 [queued]>
[2020-11-28 18:15:19,839] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-11-28 18:15:19,839] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2020-11-28 18:15:19,839] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-11-28 18:15:19,848] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): Write_csv_data_to_db> on 2020-11-28T12:45:10.631103+00:00
[2020-11-28 18:15:19,850] {standard_task_runner.py:54} INFO - Started process 16489 to run task
[2020-11-28 18:15:19,885] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'Write_data_to_postgres_then_to_elasticsearch', 'Write_csv_data_to_db', '2020-11-28T12:45:10.631103+00:00', '--job_id', '426', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/csv_pg_elasticsearch.py', '--cfg_path', '/var/folders/ff/pqhf5klx0msdsn3m1cnq4cxr0000gn/T/tmpitrivlzy']
[2020-11-28 18:15:19,888] {standard_task_runner.py:78} INFO - Job 426: Subtask Write_csv_data_to_db
[2020-11-28 18:15:19,949] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: Write_data_to_postgres_then_to_elasticsearch.Write_csv_data_to_db 2020-11-28T12:45:10.631103+00:00 [running]> 47.43.168.192.in-addr.arpa
[2020-11-28 18:15:19,991] {taskinstance.py:1150} ERROR - invalid byte sequence for encoding "UTF8": 0xae
CONTEXT:  COPY sampletable, line 1
Traceback (most recent call last):
  File "/Users/yudi/opt/anaconda3/envs/airflow/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/yudi/opt/anaconda3/envs/airflow/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/Users/yudi/opt/anaconda3/envs/airflow/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/yudi/airflow/dags/csv_pg_elasticsearch.py", line 66, in write_data
    cur.copy_from(f, "sampletable", sep=",")
psycopg2.errors.CharacterNotInRepertoire: invalid byte sequence for encoding "UTF8": 0xae
CONTEXT:  COPY sampletable, line 1

[2020-11-28 18:15:19,993] {taskinstance.py:1194} INFO - Marking task as FAILED. dag_id=Write_data_to_postgres_then_to_elasticsearch, task_id=Write_csv_data_to_db, execution_date=20201128T124510, start_date=20201128T124519, end_date=20201128T124519
[2020-11-28 18:15:24,781] {local_task_job.py:102} INFO - Task exited with return code 1
